-- 20260507_add_rls_policies.sql
-- Run this in your Supabase SQL Editor to allow clients to upload documents.

-- 1. Disable RLS on the documents table
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;

-- 2. Create the missing calendar_events table
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    event_name TEXT NOT NULL,
    event_date DATE NOT NULL,
    entity_id BIGINT, -- Optional reference to an entity
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Public Access for Storage (Since Bucket RLS is still blocking uploads)
-- Note: This is for the 'documents' bucket you just created.
-- Run these as individual statements if your editor complains.
CREATE POLICY "Public Access for Documents Bucket" ON storage.objects FOR ALL USING (bucket_id = 'documents');
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
